aco_config:
    - model: "CKCC" # 4i
      name_pattern: "C\\d{4}"
      performance_year_transition: "01/01"
      lookback_period: 2
      data:
        - "adjudicated"
    - model: "KCF" # 4i
      name_pattern: "K\\d{4}"
      performance_year_transition: "01/01"
      lookback_period: 2
      data:
        - "adjudicated"
    - model: "DC" # 4i
      name_pattern: "D\\d{4}"
      performance_year_transition: "04/01"
      lookback_period: 3
      data:
        - "partially-adjudicated"
        - "adjudicated"
    - model: "SSP" # ACO-MS
      name_pattern: "^A\\d{4}"
      data:
        - "adjudicated"
    - model: "CEC" # inactive
      name_pattern: "E\\d{4}"
      data:
        - "adjudicated"
    - model: "NGACO" # inactive
      name_pattern: "V\\d{3}"
      data:
        - "adjudicated"
    - model: "TEST"
      name_pattern: "TEST\\d{3}"
      data:
        - "adjudicated"
        - "partially-adjudicated"
    - model: "TCOCMD" # BCDA Admin
      name_pattern: "CT\\d{6}"
      data:
        - "adjudicated"
        - "partially-adjudicated"
      attribution_file:
        file_type: "csv"
        name_pattern: '(P|T)\.(PCPB)\.(M)([0-9][0-9])(\d{2})\.(D\d{6}\.T\d{6})\d'
        model_identifier: "PCPB"
        file_performance_year: 4
        file_date: 6
        metadata_matches: 7
      ignore_suppressions: true
    - model: "CDAC" # IHP
      name_pattern: "DA\\d{4}"
      data:
        - "adjudicated"
        - "partially-adjudicated"
      attribution_file:
        file_type: "csv"
        name_pattern: '(P|T)\.(BCD)\.(DA\d{4}).(MBIY)(\d{2})\.(D\d{6}\.T\d{6})\d'
        model_identifier: "BCD"
        file_performance_year: 5
        file_date: 6
        metadata_matches: 7
    - model: "GUIDE"
      name_pattern: "GUIDE-\\d{5}"
      data:
      attribution_file:
        file_type: "csv"
        name_pattern: '(P|T)\.(GUIDE)\.(GUIDE-)(\d{5})\.(Y)(\d{2})\.(D\d{6}\.T\d{6})\d'
        model_identifier: "GUIDE"
        file_performance_year: 5
        file_date: 6
        metadata_matches: 7
rate_limit_config:
  all: true
  acos: []
v3_enabled_acos:
  - "A1234"
  - "A5678"
  - "A9990"
  - "CT123456"
  - "TEST994"